// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXcvrFrLzcXS4tCgAGElBXUOLwG08R34E',
    appId: '1:519762023801:web:50fc985480289ba55c8ba8',
    messagingSenderId: '519762023801',
    projectId: 'collab-with-dkv',
    authDomain: 'collab-with-dkv.firebaseapp.com',
    storageBucket: 'collab-with-dkv.firebasestorage.app',
    measurementId: 'G-7RY4SXV5V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQgNF3wMkk97bXY_XyNcxeeZLVZvYBXsA',
    appId: '1:519762023801:android:d55095eb4d1b63e45c8ba8',
    messagingSenderId: '519762023801',
    projectId: 'collab-with-dkv',
    storageBucket: 'collab-with-dkv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ9emXUWNC4tNac-zNYcE_yvj-h9ZcatQ',
    appId: '1:519762023801:ios:cb48d1ec9eb877875c8ba8',
    messagingSenderId: '519762023801',
    projectId: 'collab-with-dkv',
    storageBucket: 'collab-with-dkv.firebasestorage.app',
    iosBundleId: 'com.example.syifaLaundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ9emXUWNC4tNac-zNYcE_yvj-h9ZcatQ',
    appId: '1:519762023801:ios:cb48d1ec9eb877875c8ba8',
    messagingSenderId: '519762023801',
    projectId: 'collab-with-dkv',
    storageBucket: 'collab-with-dkv.firebasestorage.app',
    iosBundleId: 'com.example.syifaLaundry',
  );
}
